<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{8e29b5fc-8f50-4b03-9cb8-d6b39838dd83}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    Estacion: FB_Estacion;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF NOT Estacion.i_SelectorManual THEN
	Estacion();
END_IF;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="12" Count="1" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>